package tls.utils.der;

extern enum OID {
	COMMON_NAME;
	COUNTRY_NAME;
	DH_PUBLIC_NUMBER;
	DSA;
	DSA_WITH_SHA1;
	LOCALITY_NAME;
	MD2_WITH_RSA_ENCRYPTION;
	MD5_WITH_RSA_ENCRYPTION;
	ORGANIZATION_NAME;
	ORG_UNIT_NAME;
	RSA_ENCRYPTION;
	SHA1_WITH_RSA_ENCRYPTION;
	STATE_NAME;
	SURNAME;
	TITLE;
}
