name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup haxe
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib
          haxelib dev hxmpp .
          haxelib install hxnodejs
          haxelib install utest
      - name: Run unit tests
        run: haxe test.hxml
      - name: Build haxedoc.xml
        run: haxe haxedoc.hxml
      - name: Build example client
        run: haxe --cwd example nodejs.hxml
